sudo: required
dist: xenial
language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - nightly

before_install:
  - sudo apt-get update -q

  # create and start a local traccar server
  - wget https://github.com/traccar/traccar/releases/download/v4.2/traccar-linux-64-4.2.zip
  - unzip traccar-linux-64-4.2.zip
  - sudo ./traccar.run
  - cd /opt/traccar/
  - sudo service traccar start

install:
 - pip install requests
 - pip install pytest

before_script:
 - cd $TRAVIS_BUILD_DIR

script:
 - python -m pytest
