sudo: required
dist: xenial
language: python

python:
  - 3.5
  - 3.6

addons:
  mariadb: 10.3

before_install:
  - sudo apt-get update -q
  - sudo apt-get install
  - mysql -u root -e 'CREATE DATABASE traccar;'
  - mysql -u root -e "CREATE USER 'traccar'@'localhost' IDENTIFIED BY 'traccar';"
  - mysql -u root -e "GRANT ALL ON traccar.* TO 'traccar'@'localhost';"

  - wget https://github.com/traccar/traccar/releases/download/v4.2/traccar-linux-64-4.2.zip
  - unzip traccar-linux-64-4.2.zip
  - sudo ./traccar.run
  - wget https://raw.githubusercontent.com/Legacier/pytraccar/master/tests/traccar.xml
  - sudo mv traccar.xml /opt/traccar/conf/

  - cd /opt/traccar/
  - sudo service traccar start

install:
 - pip install requests
 - pip install pytest

before_script:
 - cd $TRAVIS_BUILD_DIR

script:
 - python -m pytest
