sudo: required
language: python

python:
  - 3.5
  - 3.6

addons:
  mariadb: 10.3

before_install:
  - sudo apt-get update
  - mysql -u root -e 'CREATE DATABASE traccar;'
  - mysql -u root -e "CREATE USER 'traccar'@'localhost' IDENTIFIED BY 'traccar';"
  - mysql -u root -e "GRANT ALL ON traccar.* TO 'traccar'@'localhost';"

install:
 - pip install requests
 - pip install pytest

script:
 - python -m pytest
